version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
       - "5433:5432"  # Mude de 5432 para 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_api
    command: ["/app/entrypoint.sh"]  # Agora usa o entrypoint para gerenciar o servidor
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase

volumes:
  postgres_data:
